### ISSUE TITLE
Need to restart VSCode if SFTP connection fails

### ISSUE THREAD

**Issue by stefanofiorentino** [wspl/vscode-sync#1]
Hi, 
  when connection fails (it occours often when you work with IoT system which you restart frequently)
the sync package stuck and you need to restart the package.
Is there a way to set in a server reply timeout?

**Comment by wspl** [comment]
Hello,
If connection fails, you can re-save `.vscode-sync.json` file in your root path. The extension will reconnect(meanwhile, all errors might be ignored) to server.

If you want to stop using this extension, you can rename `.vscode-sync.json` file in your root path.

And the error handling / commands of this extension is not so good, please give me some time to repair.

Of course, I'm also welcome everyone contribute code to this project.

Thank you for your issues. Any other questions?

**Comment by stefanofiorentino** [comment]
Hi, I'm not a TS coder, but I can give it a try.
It saves me a lot of time to upload manually to RPi server.
Anyway, well done!

2015-12-08 14:33 GMT+01:00 Plutonist notifications@github.com:

> If connection fails, you can re-save .vscode-sync.json file in your root
> path. The extension will reconnect(meanwhile, all errors might be ignored).
> 
> If you want to stop using this extension, you can rename .vscode-sync.json
> file in your root path.
> 
> And the he error handle of this extension is not so good, please give me
> some time to repair.
> 
> Of course, I'm also welcome everyone contribute code to this project.
> 
> Thank you for your issues.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wspl/vscode-sync/issues/1#issuecomment-162880566.

## 

Ing. Stefano Fiorentino
Cell. +39 340 2216385
